#!/bin/env bash
#PBS -l select=${N_CHUNKS}:ncpus=${N_CPUS_PER_CHUNK}:mpiprocs=${N_MPI_PER_CHUNK}:mem=2gb
#PBS -l place=${PLACE}:excl
#PBS -l walltime=${WALLTIME}
#PBS -q shortCPUQ

# output & error files
#PBS -N ${JOB_NAME}_${N_PROC}_${N_THRD}

module load OpenMPI/4.1.6-GCC-13.2.0

export OMP_NUM_THREADS=${N_THRD}
export OMP_PLACES=cores
export OMP_PROC_BIND=close

sort -u "$PBS_NODEFILE" | awk '{print $1" slots=${N_CPUS_PER_CHUNK}"}' > hosts_${N_PROC}_${N_THRD}

mpirun --hostfile hosts_${N_PROC}_${N_THRD} -np ${N_PROC} \
  --map-by ppr:${N_MPI_PER_CHUNK}:node:PE=${N_THRD} \
  --bind-to core \
  ./parallel-sso/sso_hybrid_sharks -p ${P} -d ${D} -k ${K} -m ${M} -t ${N_THRD}