#!/bin/env bash
#PBS -l select=1:ncpus=1:mem=2gb
#PBS -l walltime=0:15:00
#PBS -l place=pack:excl
#PBS -q shortCPUQ
#PBS -N ${JOB_NAME}

module load OpenMPI/4.1.6-GCC-13.2.0

./parallel-sso/sso_serial_v2 -p ${POP} -d ${DIMS} -k ${STAGES} -m ${ROT}