#!/bin/env bash
#PBS -l select=${N_CPUS}:ncpus=${N_THRD}:mem=2gb
#PBS -l place=${PLACE}:excl
#PBS -l walltime=${WALLTIME}
#PBS -q shortCPUQ

# output & error files
#PBS -N ${JOB_NAME}_${N_THRD}

module load OpenMPI/4.1.6-GCC-13.2.0

./parallel-sso/sso_openmp_hybrid -p ${P} -d ${D} -k ${K} -m ${M} -t $(( ${N_CPUS} * ${N_THRD} ))